<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260903140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Align generated Doctrine defaults, indexes, and Messenger storage';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE profile_attribute_value ALTER version SET DEFAULT 1');
        $this->addSql('ALTER INDEX idx_profile_value_user RENAME TO IDX_930915A8A76ED395');
        $this->addSql('ALTER INDEX idx_profile_value_attribute RENAME TO IDX_930915A8B6E62EFA');
        $this->addSql('ALTER TABLE app_user ALTER version SET DEFAULT 1');
        $this->addSql("COMMENT ON COLUMN app_user.created_at IS ''");
        $this->addSql('ALTER TABLE attribute ALTER version SET DEFAULT 1');
        $this->addSql("COMMENT ON COLUMN attribute.updated_at IS ''");
        $this->addSql("COMMENT ON COLUMN attribute.last_used_at IS ''");
        $this->addSql('ALTER INDEX uniq_attr_name RENAME TO UNIQ_FA7AEFFB5E237E06');
        $this->addSql('ALTER TABLE project ALTER version SET DEFAULT 1');
        $this->addSql("COMMENT ON COLUMN project.period_start IS ''");
        $this->addSql("COMMENT ON COLUMN project.period_end IS ''");
        $this->addSql('ALTER INDEX idx_project_owner RENAME TO IDX_2FB3D0EE7E3C61F9');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE profile_attribute_value ALTER version DROP DEFAULT');
        $this->addSql('ALTER INDEX IDX_930915A8A76ED395 RENAME TO idx_profile_value_user');
        $this->addSql('ALTER INDEX IDX_930915A8B6E62EFA RENAME TO idx_profile_value_attribute');
        $this->addSql('ALTER TABLE app_user ALTER version DROP DEFAULT');
        $this->addSql("COMMENT ON COLUMN app_user.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER TABLE attribute ALTER version DROP DEFAULT');
        $this->addSql("COMMENT ON COLUMN attribute.updated_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN attribute.last_used_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER INDEX UNIQ_FA7AEFFB5E237E06 RENAME TO uniq_attr_name');
        $this->addSql('ALTER TABLE project ALTER version DROP DEFAULT');
        $this->addSql("COMMENT ON COLUMN project.period_start IS '(DC2Type:date_immutable)'");
        $this->addSql("COMMENT ON COLUMN project.period_end IS '(DC2Type:date_immutable)'");
        $this->addSql('ALTER INDEX IDX_2FB3D0EE7E3C61F9 RENAME TO idx_project_owner');
    }
}