<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260903190000 extends AbstractMigration
{
    public function getDescription(): string { return 'Create append-only position discussion posts'; }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE discussion_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position_id INT NOT NULL, author_id INT NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DISCUSSION_POSITION ON discussion_post (position_id)');
        $this->addSql('CREATE INDEX IDX_DISCUSSION_AUTHOR ON discussion_post (author_id)');
        $this->addSql('ALTER TABLE discussion_post ADD CONSTRAINT FK_DISCUSSION_POSITION FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE discussion_post ADD CONSTRAINT FK_DISCUSSION_AUTHOR FOREIGN KEY (author_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void { $this->addSql('DROP TABLE discussion_post'); }
}