<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260903180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create projected candidate CV records';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE cv (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, candidate_id INT NOT NULL, position_id INT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT DEFAULT 1 NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_cv_candidate_position ON cv (candidate_id, position_id)');
        $this->addSql('CREATE INDEX IDX_B66FFE9291BD8781 ON cv (candidate_id)');
        $this->addSql('CREATE INDEX IDX_B66FFE92DD842E46 ON cv (position_id)');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_CV_CANDIDATE FOREIGN KEY (candidate_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_CV_POSITION FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE cv');
    }
}