<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260903100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the shared attribute library and built-in profile attributes';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, category VARCHAR(30) NOT NULL, description TEXT NOT NULL, type VARCHAR(20) NOT NULL, options JSON NOT NULL, is_builtin BOOLEAN NOT NULL, version INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_Attr_NAME ON attribute (name)');
        $this->addSql('COMMENT ON COLUMN attribute.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN attribute.last_used_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql("INSERT INTO attribute (name, category, description, type, options, is_builtin, version, updated_at) VALUES ('First Name', 'personal', 'Candidate first name', 'string', '[]', TRUE, 1, CURRENT_TIMESTAMP), ('Last Name', 'personal', 'Candidate last name', 'string', '[]', TRUE, 1, CURRENT_TIMESTAMP), ('Location', 'contact', 'Candidate location', 'string', '[]', TRUE, 1, CURRENT_TIMESTAMP), ('Photo', 'personal', 'External profile photo URL', 'image', '[]', TRUE, 1, CURRENT_TIMESTAMP)");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE attribute');
    }
}