<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260903200000 extends AbstractMigration
{
    public function getDescription(): string { return 'Create recruiter CV likes'; }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cv_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cv_id INT NOT NULL, recruiter_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_cv_like ON cv_like (cv_id, recruiter_id)');
        $this->addSql('CREATE INDEX IDX_CV_LIKE_CV ON cv_like (cv_id)');
        $this->addSql('CREATE INDEX IDX_CV_LIKE_RECRUITER ON cv_like (recruiter_id)');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CV_LIKE_CV FOREIGN KEY (cv_id) REFERENCES cv (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CV_LIKE_RECRUITER FOREIGN KEY (recruiter_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void { $this->addSql('DROP TABLE cv_like'); }
}