<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260903120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create candidate profile values and projects';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE profile_attribute_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, attribute_id INT NOT NULL, value TEXT DEFAULT NULL, version INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_PROFILE_VALUE_USER ON profile_attribute_value (user_id)');
        $this->addSql('CREATE INDEX IDX_PROFILE_VALUE_ATTRIBUTE ON profile_attribute_value (attribute_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROFILE_ATTRIBUTE ON profile_attribute_value (user_id, attribute_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, name VARCHAR(160) NOT NULL, period_start DATE DEFAULT NULL, period_end DATE DEFAULT NULL, description TEXT NOT NULL, tags JSON NOT NULL, version INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_PROJECT_OWNER ON project (owner_id)');
        $this->addSql('ALTER TABLE profile_attribute_value ADD CONSTRAINT FK_PROFILE_VALUE_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_attribute_value ADD CONSTRAINT FK_PROFILE_VALUE_ATTRIBUTE FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_PROJECT_OWNER FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN project.period_start IS '(DC2Type:date_immutable)'");
        $this->addSql("COMMENT ON COLUMN project.period_end IS '(DC2Type:date_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE profile_attribute_value');
    }
}