<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260903160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create positions, selected attributes, and access rules';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, short_description TEXT NOT NULL, is_public BOOLEAN NOT NULL, company VARCHAR(160) DEFAULT NULL, level VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT DEFAULT 1 NOT NULL, project_tags JSON NOT NULL, max_projects INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE position_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_POSITION_ATTRIBUTE_POSITION ON position_attribute (position_id)');
        $this->addSql('CREATE INDEX IDX_POSITION_ATTRIBUTE_ATTRIBUTE ON position_attribute (attribute_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_POSITION_ATTRIBUTE ON position_attribute (position_id, attribute_id)');
        $this->addSql('CREATE TABLE position_access_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, operator VARCHAR(20) NOT NULL, comparison_value TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_POSITION_RULE_POSITION ON position_access_rule (position_id)');
        $this->addSql('CREATE INDEX IDX_POSITION_RULE_ATTRIBUTE ON position_access_rule (attribute_id)');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_POSITION_ATTRIBUTE_POSITION FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_POSITION_ATTRIBUTE_ATTRIBUTE FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_POSITION_RULE_POSITION FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_POSITION_RULE_ATTRIBUTE FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN position.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN position.updated_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE position_access_rule');
        $this->addSql('DROP TABLE position_attribute');
        $this->addSql('DROP TABLE position');
    }
}